language: go
go:
  - "1.10"
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - make release_deps
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
after_success:
  - make cross_build
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'dist/*'
  on:
    tags: true
